### ISSUE TITLE
IWR6843 ODS support

### ISSUE THREAD

**Issue by jensJJ** [m6c7l/pymmw#1]
Hello nice tool, is it possible to also use the IWR6843 ODS? Thanks

**Comment by m6c7l** [comment]
Currently, the tool supports IWR1443 only as we had access to that type of device on-site. In a further development, IWR6843 could become supported, since we need to have at least one device on-site for testing. Cheers

**Comment by jensJJ** [comment]
I can supply you remote access to my IWR6843ISK ODS + MMWAVEICBOOST, if that would help. I have loaded 3D People Counting firmware and would like to read the X,Y,Z coordinates of the point-cloud via Python. It seems to be very similar via COM Port data reading.  I think many things of the can also be taken from here https://github.com/bigheadG/mmWave/tree/master/PC3D-ES2.

**Comment by m6c7l** [comment]
Thank you for your offer. Unfortunately, we need physical access, and of course some time to any device we have never seen before to let it become supported in the software.
