### ISSUE TITLE
Trouble getting the software to run with IWR6843AOP and Mmwaveicboost board

### ISSUE THREAD

**Issue by MickReich** [m6c7l/pymmw#12]
Hi, I have managed to successfully run the OOB mmWave demo Visualizer software (3.5)  but I get the following upon pressing NRST on the Boost board.

mmwDemo:/>******************************************

xWR64xx MMW Demo 03.05.00.04

******************************************

Note well : not xWR68xx  ! Do not understand why this happening.

Running pymmw software locates the com ports automatically (ACM0 and ACM1) but just generates the message "pymmw _read_ no handler found" . Tracing through the code I suspect the issue is with the initialization where it checks for the appropriate firmware and finds xWR64xx not xWR68xx.

Is there a way to force the correct loading of the handler or some other work around?

Thanks,
Mike

**Comment by m6c7l** [comment]
Hi,
I suggest to add „xWR64xx“ to „meta[„dev“]“ in „mss/x8_mmw“ and give it a try. I also do not understand why the firmware is showing „xWR64xx“ on your IWR68xx. In any case, I would re-flash the device with an official firmware from TI (again) if things do not work as expected.
