### ISSUE TITLE
ModuleNotFoundError: No module named 'serial'

### ISSUE THREAD

**Issue by Niklas200000** [m6c7l/pymmw#16]
Hey,

I tried to use your python code but I´m not able to get it to work. I use the Ti IWR6843 with the MMWAVEICBOOST carrier card. I programmed the chip with the xwr68xx_mmw_demo.bin form the mmwave_sdk_03_05_00_04. 

When I try to start the programm I get the error:  ModuleNotFoundError: No module named 'serial'

Can you help me to get it to work?

**Comment by m6c7l** [comment]
Hey,
try to install the pyserial module in your Python environment: `pip install pyserial`.
The module is used for the communication to the device via USB and should be available after installation.

**Comment by Niklas200000** [comment]
That worked!
Now I have an other problem. 

usage: pymmw.py [-h] -c CONTROL_PORT -d DATA_PORT [-f FORCE_HANDLER] [-n]
pymmw.py: error: the following arguments are required: -c/--control-port, -d/--data-port
An exception has occurred, use %tb to see the full traceback.

SystemExit: 2

The traceback show me this:
line 1820, in parse_args
    args, argv = self.parse_known_args(args, namespace)
line 1853, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
line 2090, in _parse_known_args
    self.error(_('the following arguments are required: %s') %
line 2577, in error
    self.exit(2, _('%(prog)s: error: %(message)s\n') % args)
 line 2564, in exit
    _sys.exit(status)

SystemExit: 2

Would be really nice if you can help me again.

**Comment by m6c7l** [comment]
it seems you are running pymmw.py with another interpreter than python(3), e.g. ipython, or trying to run it in a juypter notebook. try to run pymmw.py with python (on the console, i.e. cmd on windows).

**Comment by Niklas200000** [comment]
It ist still not running. I send you a Mail with my contact details that we maybe find the Problem faster.
