### ISSUE TITLE
stuck on "waiting for reset (NRST) of the device"

### ISSUE THREAD

**Issue by tingyuau** [m6c7l/pymmw#4]
hi there, 

I would like to understand what is the expected behaviour when calling pymmw.py?

I have given it the control port and data port arguments and it was able to print control port: /dev/ttyACM0 and data port: /dev/ttyACM1 so I think it was recognising the ports.

However the programme is now stuck on "waiting for reset (NRST) of the device". Am I supposed to hit the reset button on the sensor as that's what I did but nothing happened?

Thanks

**Comment by KamiCalcium** [comment]
I faced the same issue and couldn't solve it when I'm using Windows. What's your model? IWR1443 ES3.0?

**Comment by m6c7l** [comment]
Hi there,
please update pymmw with the most recent version from this repository (06bb18c9cb11cd1c96376e0c1ba77ae6ce711c67) and try again utilizing the **--no-discovery** option (https://github.com/m6c7l/pymmw#troubleshooting).
