### ISSUE TITLE
IWR1443 ES3.0 3D point cloud

### ISSUE THREAD

**Issue by KamiCalcium** [m6c7l/pymmw#5]
Hi,

Thank you for the amazing software.

I'm using IWR1443 ES3.0 (with SDK 2.1) and trying to get 3D point cloud. I tried many of the TI official product but failed all of them (mmWave demo visualizer 2.1.0~3.0.0, roslaunch the 1443_3d rviz from other github but looks like only support ES2.0). It looks like they really don't update software/firmware for IWR1443 now. The only thing work is the mmWave studio 2.1.0 but it does not have a 3D point cloud.

It looks like your software is supporting IWR1443 ES3.0 (SDK 2.1) 3D point cloud plotting. I tried it in Windows but I failed just like https://github.com/m6c7l/pymmw/issues/4 Now I plan to try in Ubuntu 20.04 and having the "No handler found" issue. But I believe this is fixable. I installed 
pyserial (3.4)
pyusb (1.0.2)
matplotlib (3.3.1)
numpy (1.19.1)
since rest of the packages are not related to CFAR detected objects (point cloud).

To clarify, I should first run the pymmw.py with the correct ports(it will call 14_capture.py itself), then I run the application, which is plot_detected_objects.py. Is that the correct procedure? 

Second problem: SDK2.1 you mean flash the xwr12xx_xwr14xx_masterss.bin and xwr12xx_xwr14xx_radarss.bin from mmwave_studio_02_01_01_00. Is that correct? Please correct me if I'm wrong.

Also, I suggest you guys post a video demo along with the source code. I believe it will help other users a lot. Thank you very much!!

**Comment by m6c7l** [comment]
Please have a look at #4.
