### ISSUE TITLE
Further instructions for usage

### ISSUE THREAD

**Issue by anjanettec** [m6c7l/pymmw#8]
Hi, 
I am trying to use the Pythonic mmWave Toolbox you wrote and I am unsure of what the next steps are after getting to this stage
![image](https://user-images.githubusercontent.com/40926553/120332489-b4695280-c2e6-11eb-8a32-66fdbf56f278.png)
what exactly can I input into the "mmwaveDemo:/> "section. 
I currently have the IWR6843AOP. 
Thanks in advanced.

**Comment by m6c7l** [comment]
Hi,
please add the version of the firmware your are using (`03.05.00.04`) to the tuple in mss/x8_mmw.py at line 25 (ver) and try again. Please report if it works.
Best
